service: serverless-playgrounds

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  environment:
    FUNCTION_NAME_PREFIX: ${self:service}-${self:provider.stage}

plugins:
  - serverless-delete-loggroups
  - serverless-webpack

custom:
  webpack:
    packager: yarn

functions:
  hello:
    handler: src/index.hello
