service: serverless-playgrounds

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 10

plugins:
  - serverless-delete-loggroups
  - serverless-webpack

custom:
  webpack:
    packager: yarn

functions:
  hello:
    handler: src/index.hello
